export const ROLES = {
  SUPER_ADMIN: "SUPER_ADMIN",
  ADMIN: "ADMIN",
  ASSISTANT: "ASSISTANT",
  SUPERVISOR: "SUPERVISOR",
  SUPER_CLERK: "SUPER_CLERK",
  CLERK: "CLERK",
  TEACHER: "TEACHER",
  SUPER_STUDENT: "SUPER_STUDENT",
  STUDENT: "STUDENT",
} as const

export type Role = (typeof ROLES)[keyof typeof ROLES]

export const STAFF_ROLES: Role[] = [
  ROLES.ADMIN,
  ROLES.ASSISTANT,
  ROLES.SUPERVISOR,
  ROLES.SUPER_CLERK,
  ROLES.CLERK,
  ROLES.TEACHER,
]

export const STUDENT_ROLES: Role[] = [ROLES.STUDENT, ROLES.SUPER_STUDENT]
