export const ROLES = {
  SUPER_ADMIN: "SUPER_ADMIN",
  ADMIN: "ADMIN",
  ASSISTANT: "ASSISTANT",
  SUPERVISOR: "SUPERVISOR",
  SUPER_CLERK: "SUPER_CLERK",
  CLERK: "CLERK",
  TEACHER: "TEACHER",
  SUPER_STUDENT: "SUPER_STUDENT",
  STUDENT: "STUDENT",
} as const

export type Role = (typeof ROLES)[keyof typeof ROLES]
