export const CLASS_DELIVERY_MODES = ["IN_PERSON", "ONLINE"] as const

export const SCHEDULING_RUN_STATUSES = [
  "QUEUED",
  "PREFLIGHT_FAILED",
  "GENERATING",
  "COMPLETED",
  "FAILED",
  "CANCELLED",
] as const

export const SCHEDULING_PLAN_STATUSES = [
  "DRAFT",
  "SELECTED",
  "PUBLISHED",
  "REJECTED",
  "SUPERSEDED",
] as const

export const SCHEDULING_TIME_GROUPS = [
  "ODD_MORNING",
  "ODD_EVENING",
  "EVEN_MORNING",
  "EVEN_EVENING",
  "NEUTRAL_MORNING",
  "NEUTRAL_EVENING",
  "MIXED_MORNING",
  "MIXED_EVENING",
] as const

export const SCHEDULING_SCORE_STATUSES = [
  "APPLICABLE",
  "NOT_APPLICABLE",
] as const

export const SCHEDULING_WARNING_SEVERITIES = ["INFO", "WARNING"] as const

export const SCHEDULING_WARNING_SCOPES = [
  "INPUT",
  "PLAN",
  "PROPOSAL",
  "REQUIREMENT",
] as const

export const SCHEDULING_SELECTION_REASON_CODES = [
  "MAXIMIZES_STUDENT_COVERAGE",
  "IMPROVES_TIME_DIVERSITY",
  "MATCHES_TEACHER_QUALIFICATION",
  "MATCHES_TEACHER_AVAILABILITY",
  "BALANCES_TEACHER_LOAD",
  "ONLY_FEASIBLE_HARD_CONSTRAINT_OPTION",
  "MANUALLY_SELECTED",
] as const

export const SCHEDULING_HARD_CONSTRAINT_CODES = [
  "INCOMPLETE_CLASS_REQUIREMENT",
  "INVALID_TEACHER",
  "TEACHER_NOT_QUALIFIED",
  "OUTSIDE_TEACHER_AVAILABILITY",
  "TEACHER_TIME_CONFLICT",
  "INVALID_DELIVERY_LOCATION",
  "INSUFFICIENT_CLASSROOM_CAPACITY",
  "CLASSROOM_TIME_CONFLICT",
] as const

export const SCHEDULING_PLAN_VALIDATION_CODES = [
  "CROSS_INSTITUTE_REFERENCE",
  "INVALID_OR_INACTIVE_REFERENCE",
  "INCOMPLETE_CLASS_REQUIREMENT",
  "INVALID_TIME_RANGE",
  "SESSION_OUTSIDE_TERM",
  "INVALID_TEACHER",
  "TEACHER_NOT_QUALIFIED",
  "OUTSIDE_TEACHER_AVAILABILITY",
  "TEACHER_TIME_CONFLICT",
  "INVALID_DELIVERY_LOCATION",
  "INSUFFICIENT_CLASSROOM_CAPACITY",
  "CLASSROOM_TIME_CONFLICT",
  "REQUIREMENT_CADENCE_MISMATCH",
  "INVALID_SESSION_DATES",
] as const

export const SCHEDULING_UNRESOLVED_REASON_CODES = [
  "INVALID_REQUIREMENT",
  "NO_VALID_TEACHER",
  "NO_QUALIFIED_TEACHER",
  "NO_TEACHER_AVAILABILITY",
  "TEACHER_TIME_CONFLICT",
  "NO_COMPATIBLE_CLASSROOM",
  "INSUFFICIENT_CLASSROOM_CAPACITY",
  "CLASSROOM_TIME_CONFLICT",
  "NO_FEASIBLE_TIME_SLOT",
  "INSUFFICIENT_FEASIBLE_CANDIDATES",
  "PLAN_COMBINATION_CONFLICT",
] as const

export const SCHEDULING_TIME_REGEX = /^([01]\d|2[0-3]):([0-5]\d)$/
export const SCHEDULING_CODE_REGEX = /^[A-Z][A-Z0-9_]*$/

export type ClassDeliveryMode = (typeof CLASS_DELIVERY_MODES)[number]
export type SchedulingRunStatus = (typeof SCHEDULING_RUN_STATUSES)[number]
export type SchedulingPlanStatus = (typeof SCHEDULING_PLAN_STATUSES)[number]
export type SchedulingTimeGroup = (typeof SCHEDULING_TIME_GROUPS)[number]
export type SchedulingScoreStatus = (typeof SCHEDULING_SCORE_STATUSES)[number]
export type SchedulingWarningSeverity =
  (typeof SCHEDULING_WARNING_SEVERITIES)[number]
export type SchedulingWarningScope = (typeof SCHEDULING_WARNING_SCOPES)[number]
export type SchedulingSelectionReasonCode =
  (typeof SCHEDULING_SELECTION_REASON_CODES)[number]
export type SchedulingHardConstraintCode =
  (typeof SCHEDULING_HARD_CONSTRAINT_CODES)[number]
export type SchedulingPlanValidationCode =
  (typeof SCHEDULING_PLAN_VALIDATION_CODES)[number]
export type SchedulingUnresolvedReasonCode =
  (typeof SCHEDULING_UNRESOLVED_REASON_CODES)[number]
